### PR TITLE
add command line option to input the num_inter_threads and num_intra_…

### PR DESCRIPTION
**Pull request by cuixiaom**
…threads to control threads of session

On CPU side of training, the config_proto.inter_op_parallelism_threads and config_proto.intra_op_parallelism_threads significantly impact performance, the default value of these two parameter doesn't guarantee the best performance, it should have capability to let user to decide these two parameters.

### CODE REVIEW

**Comment by cuixiaom** [comment]
I signed it!

**Comment by oahziur** [comment]
@cuixiaom I think you need to associate the commit with the email address you signed the CLA.

Do you know what value user should set in order to get a good performance on CPU? some comparison among different configurations would be very useful. 

Thanks,
Rui

**Comment by cuixiaom** [comment]
@oahziur I have CLA covered with this email address. Please verify.
For your question, we did see the performance variance with different CPU threads. For my experience, the threads should be closed to the number of cores of CPU. but sometimes, it will not true depends on the availability of resources. it depends on users' the system configuration.

**Comment by oahziur** [comment]
@cuixiaom I think the problem with CLA is that you need to associate the email address with your git commit, otherwise, I think the CLA check won't pass. For example, if I open your commit, it shows unrecognized author.

**Comment by cuixiaom** [comment]
@oahziur I have create a new PR since this PR is messed up with CLA and account information issue. Please check the new PR I created. https://github.com/tensorflow/nmt/pull/194
Thanks!

**Pull request closed without merging**
