### PR TITLE
Iterator error fix

### PR DESCRIPTION
**Pull request by rpryzant**
Iterator has the comment 

`Subtract one from the target to avoid counting the target_input <eos> tag (resp. target_output <sos> tag).`

But this isn't being done. I think my change fixes this?

### CODE REVIEW

**Comment by oahziur** [comment]
Thanks!

The latest commit looks good since I think we want to make sure the model can generate <eos> correctly.

**Comment by bastings** [comment]
Something does seem to be wrong with the iterator though. This happens trying to reproduce the vi-en results (python3.5, tf1.2.1), at every evaluation:

```
  loaded infer model parameters from ./models/nmt_att_vi_en/translate.ckpt-6000, time 0.08s
# External evaluation, global step 6000
  decoding to output ./models/nmt_att_vi_en/output_dev.
2017-08-21 17:50:52.985605: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: End of sequence
         [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[-1,-1], [-1]], output_types=[DT_INT32, DT_INT32], _device="/job:localhost/replica:0/task:0/cpu:0"](Iterator)]]
2017-08-21 17:50:52.985605: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: End of sequence
         [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[-1,-1], [-1]], output_types=[DT_INT32, DT_INT32], _device="/job:localhost/replica:0/task:0/cpu:0"](Iterator)]]
2017-08-21 17:50:52.985667: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: End of sequence
         [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[-1,-1], [-1]], output_types=[DT_INT32, DT_INT32], _device="/job:localhost/replica:0/task:0/cpu:0"](Iterator)]]
2017-08-21 17:50:52.985878: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: End of sequence
         [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[-1,-1], [-1]], output_types=[DT_INT32, DT_INT32], _device="/job:localhost/replica:0/task:0/cpu:0"](Iterator)]]
2017-08-21 17:50:52.985960: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: End of sequence
         [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[-1,-1], [-1]], output_types=[DT_INT32, DT_INT32], _device="/job:localhost/replica:0/task:0/cpu:0"](Iterator)]]
  done, num sentences 1553, time 15s, Mon Aug 21 17:50:52 2017.
  bleu dev: 5.8
  saving hparams to ./models/nmt_att_vi_en/hparams
```

**Comment by rpryzant** [comment]
+1 ...I am observing similar behavior as @bastings for three en-ja datasets.

**Comment by bastings** [comment]
Actually I found out that the error is expected; at some point the iterator is out of data, and it will throw this exception. The exception is caught, but since the message seems to be printed from C++, there is no way to suppress it, except for muting all TF output e.g. like this:
```python
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
```

**Comment by rpryzant** [comment]
Great!

**Pull request closed without merging**
