### PR TITLE
print utf8 instead of unreadable binary

### PR DESCRIPTION
**Pull request by wb14123**
This will output readable translations on terminal while training.

### CODE REVIEW

**Comment by oahziur** [comment]
Thanks @wb14123! Have you tried the codebase at the head of master? I think [this line](https://github.com/tensorflow/nmt/blob/master/nmt/utils/misc_utils.py#L55) fixed similar issue as this PR.

**Comment by wb14123** [comment]
Yes, I'm using the head of master. But it doesn't fix this, because it uses string format in `train.py` and `inference.py`. For example: `"%s" % (b'abc')` will be `"b'abc'"` which type is string. So the param sent to `print_out` is cast to string, but still with the binary format.

**Comment by oahziur** [comment]
I see, should we use byte format instead of string format here? so we can send bytes to the utils function.

**Comment by wb14123** [comment]
That's is an option, too. Which one do you think is better? I can modify it if you think use byte format is better.

**Comment by oahziur** [comment]
I think using the byte format is slightly better since that will keep all the encoding/decoding inside the utils. Thanks!

**Comment by wb14123** [comment]
Hi, I've looked it up. It seems that byte format is not supported in Python 2. `type(b'%s' % b'abc')` is still string. Correct me if I'm wrong.

**Comment by oahziur** [comment]
@wb14123 I think `bytes` is an alias for `str` in python2 since there is no `bytes` type in python2. I think `isinstance(b'%s' % b'abc', bytes)` should be True in both python2 and python3.

**Comment by wb14123** [comment]
Yes, you are right. I've modified it. BTW, considering Python 3 is not supported by this project, the current code should be OK in Python 2.

**Comment by bastings** [comment]
I think this works in python3 without problem 👍 

Maybe `translation + b"\n"` is nicer than `(b"%s\n" % translation)`, but it's really a detail.

**Comment by oahziur** [comment]
Yes, the project should support Python 3 properly after merging #50. Thanks for the fixes.

**Pull request closed without merging**
